site_name: Documentation & Presentation Example
site_description: Discusses demo/presentation tips
site_author: Gary Coffey
docs_dir: docs
site_dir: site
repo_name: garyCoffey/presentationDocumentation
repo_url: https://github.com/garyCoffey/presentationDocumentation
nav:
  - Home: 'index.md'
  - Documentation:
    - Intro: 'documentation/index.md'
    - Trees: 'tech/tree.md'
    - Example: https://github.com/CodePlatoonAlumni/alumni-fe
    - Markdown Cheatsheet: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
  - Technical Diagrams:
    - Intro: 'tech/index.md'
    - Lucid Chart:
      - Example: 'tech/lucid/diagrams.md'
      - Lucid Chart Recommendations: https://www.lucidchart.com/blog/visualize-code-documentation
  - Tips for app Demo: 'demo_tips.md'
theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences