name: ci
on:
  push:
    branches:
      - main
      - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip3 install mkdocs mkdocs-material markdown pymdown-extensions
      - run: pip3 install https://github.com/bmcorser/fontawesome-markdown/archive/master.zip
      - run: pip3 install markdown-include mkdocs-git-revision-date-localized-plugin mkdocs-autolinks-plugin
      - run: mkdocs gh-deploy --force
